name: Deploy Frontend App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Application startup Test
        run: |
          npm run dev &  # Start the app in the background
          sleep 10      
          curl -I http://localhost:5174 || exit 1  # Check if the app is responding (adjust port if needed)
          pkill -f "npm run dev"  # Stop the running app

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SERVER_USERNAME }}
          script: |
            cd EKRUWASSA-ADMIN
            chmod +x ./deploy.sh && ./deploy.sh

      - name: Post-deployment check
        run: echo "Deployment completed successfully!"
